### ISSUE TITLE
你发引导的链接已经不存在了，能否更换一下新地址？

### ISSUE THREAD

**Issue by yss** [mdsb100/iPhone-ShareSDK-Titaniuim-Module-Demo#1]
guide: http://bbs.sharesdk.cn/forum.php?mod=viewthread&tid=102&page=1&extra=#pid323
链接是上面这个。

**Comment by mdsb100** [comment]
重新写个教程吧

**Comment by mdsb100** [comment]
https://github.com/mdsb100/titanium-good-practices/tree/master/ShareSDKModuleDemo
